development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:ddeedad5592b59f966e90e893df716ce@barb.redistogo.com:9873/
  channel_prefix: chat_app_production
